"""Build the Korea active ETF candidate universe CSV.

The universe is a research seed list for a domestic active equity ETF.
It intentionally mixes KOSPI and KOSDAQ common stocks across sectors, and
should be revalidated against point-in-time listings before backtesting.
"""

from __future__ import annotations

import csv
from collections import Counter
from collections.abc import Iterable
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT_DIR / "data" / "universe" / "korea_active_etf_universe_100.csv"

CSV_COLUMNS = [
    "rank",
    "ticker",
    "company_name",
    "market",
    "sector",
    "industry",
    "investment_theme",
    "universe_role",
    "selection_reason",
    "data_start_date",
    "is_active",
    "notes",
]

VALID_MARKETS = {"KOSPI", "KOSDAQ"}
VALID_ROLES = {"Core", "Growth", "Defensive", "Cyclical"}
MAX_SECTOR_WEIGHT = 0.25


def row(
    rank: int,
    ticker: str,
    company_name: str,
    market: str,
    sector: str,
    industry: str,
    investment_theme: str,
    universe_role: str,
    selection_reason: str,
    data_start_date: str,
    notes: str,
) -> dict[str, object]:
    """Create one normalized universe row."""
    return {
        "rank": rank,
        "ticker": ticker,
        "company_name": company_name,
        "market": market,
        "sector": sector,
        "industry": industry,
        "investment_theme": investment_theme,
        "universe_role": universe_role,
        "selection_reason": selection_reason,
        "data_start_date": data_start_date,
        "is_active": True,
        "notes": notes,
    }


def build_universe() -> list[dict[str, object]]:
    """Return the 100-stock domestic active ETF candidate universe."""
    note = "2026-07 기준 상장 보통주 후보; 백테스트 전 시점별 상장 여부와 거래정지 이력 확인 필요"
    kosdaq_note = note + "; KOSDAQ 유동성은 월별 거래대금 필터 재확인"
    return [
        row(
            1,
            "005930",
            "삼성전자",
            "KOSPI",
            "반도체·IT 하드웨어",
            "종합 반도체 및 IT 세트",
            "반도체, AI, 메모리",
            "Core",
            "국내 주식시장의 대표 대형주로 유동성과 장기 가격 데이터가 매우 풍부합니다.",
            "2010-01-01",
            note,
        ),
        row(
            2,
            "000660",
            "SK하이닉스",
            "KOSPI",
            "반도체·IT 하드웨어",
            "메모리 반도체",
            "HBM, AI, 메모리",
            "Core",
            "메모리와 HBM 사이클을 대표하는 고유동성 반도체 대형주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            3,
            "042700",
            "한미반도체",
            "KOSPI",
            "반도체·IT 하드웨어",
            "반도체 후공정 장비",
            "HBM, 반도체 장비",
            "Growth",
            "AI 반도체 후공정 장비 노출도가 높고 거래대금이 큰 중대형 성장주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            4,
            "039030",
            "이오테크닉스",
            "KOSDAQ",
            "반도체·IT 하드웨어",
            "레이저 반도체 장비",
            "반도체 장비",
            "Growth",
            "반도체 공정 장비 경쟁력과 KOSDAQ 대표성을 함께 갖춘 종목입니다.",
            "2010-01-01",
            kosdaq_note,
        ),
        row(
            5,
            "058470",
            "리노공업",
            "KOSDAQ",
            "반도체·IT 하드웨어",
            "반도체 테스트 소켓",
            "반도체 부품",
            "Growth",
            "높은 수익성과 장기 실적 안정성을 보이는 반도체 부품 대표주입니다.",
            "2010-01-01",
            kosdaq_note,
        ),
        row(
            6,
            "403870",
            "HPSP",
            "KOSDAQ",
            "반도체·IT 하드웨어",
            "고압 수소 어닐링 장비",
            "반도체 장비",
            "Growth",
            "첨단 공정 장비 성장성을 반영할 수 있는 KOSDAQ 대형 기술주입니다.",
            "2022-07-15",
            kosdaq_note,
        ),
        row(
            7,
            "140860",
            "파크시스템스",
            "KOSDAQ",
            "반도체·IT 하드웨어",
            "원자현미경 및 계측 장비",
            "반도체 계측",
            "Growth",
            "계측 장비의 기술 진입장벽과 수출 성장성을 가진 중형 성장주입니다.",
            "2015-12-17",
            kosdaq_note,
        ),
        row(
            8,
            "240810",
            "원익IPS",
            "KOSDAQ",
            "반도체·IT 하드웨어",
            "반도체 디스플레이 장비",
            "반도체 장비",
            "Cyclical",
            "국내 반도체 설비투자 사이클을 반영하는 장비 대표 종목입니다.",
            "2016-05-02",
            kosdaq_note,
        ),
        row(
            9,
            "036930",
            "주성엔지니어링",
            "KOSDAQ",
            "반도체·IT 하드웨어",
            "증착 장비",
            "반도체 장비",
            "Cyclical",
            "반도체와 태양광 장비 수요 회복을 포착할 수 있는 유동성 종목입니다.",
            "2010-01-01",
            kosdaq_note,
        ),
        row(
            10,
            "095340",
            "ISC",
            "KOSDAQ",
            "반도체·IT 하드웨어",
            "반도체 테스트 소켓",
            "반도체 부품",
            "Growth",
            "테스트 소켓 분야의 성장성과 고객 다변화가 있는 반도체 부품주입니다.",
            "2010-01-01",
            kosdaq_note,
        ),
        row(
            11,
            "064760",
            "티씨케이",
            "KOSDAQ",
            "반도체·IT 하드웨어",
            "반도체 공정 소재 부품",
            "반도체 소재",
            "Growth",
            "고부가 반도체 공정 소재 노출과 장기 수익성을 갖춘 후보입니다.",
            "2010-01-01",
            kosdaq_note,
        ),
        row(
            12,
            "222800",
            "심텍",
            "KOSDAQ",
            "반도체·IT 하드웨어",
            "반도체 패키지 기판",
            "패키징, 기판",
            "Cyclical",
            "메모리 패키지 기판 사이클과 IT 수요 회복을 반영하는 종목입니다.",
            "2015-08-07",
            kosdaq_note,
        ),
        row(
            13,
            "108320",
            "LX세미콘",
            "KOSPI",
            "반도체·IT 하드웨어",
            "디스플레이 구동칩 팹리스",
            "팹리스, 디스플레이",
            "Cyclical",
            "국내 팹리스와 디스플레이 수요 사이클을 함께 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            14,
            "035420",
            "NAVER",
            "KOSPI",
            "소프트웨어·인터넷·플랫폼",
            "인터넷 플랫폼",
            "AI, 검색, 커머스",
            "Core",
            "국내 인터넷 플랫폼 대표주로 장기 데이터와 유동성이 우수합니다.",
            "2010-01-01",
            note,
        ),
        row(
            15,
            "035720",
            "카카오",
            "KOSPI",
            "소프트웨어·인터넷·플랫폼",
            "모바일 플랫폼",
            "플랫폼, 콘텐츠, 핀테크",
            "Core",
            "모바일 플랫폼 생태계와 콘텐츠·금융 자회사 노출을 제공합니다.",
            "2010-01-01",
            note,
        ),
        row(
            16,
            "259960",
            "크래프톤",
            "KOSPI",
            "소프트웨어·인터넷·플랫폼",
            "게임 소프트웨어",
            "게임, 글로벌 콘텐츠",
            "Growth",
            "글로벌 게임 IP와 현금창출력을 가진 소프트웨어 대형주입니다.",
            "2021-08-10",
            note,
        ),
        row(
            17,
            "036570",
            "NC",
            "KOSPI",
            "소프트웨어·인터넷·플랫폼",
            "게임 소프트웨어",
            "게임, 콘텐츠",
            "Cyclical",
            "게임 신작 사이클과 소프트웨어 섹터 변동성을 반영합니다.",
            "2010-01-01",
            note + "; 구 엔씨소프트",
        ),
        row(
            18,
            "251270",
            "넷마블",
            "KOSPI",
            "소프트웨어·인터넷·플랫폼",
            "모바일 게임",
            "게임, 콘텐츠",
            "Cyclical",
            "모바일 게임 포트폴리오와 신작 모멘텀 분석에 적합합니다.",
            "2017-05-12",
            note,
        ),
        row(
            19,
            "112040",
            "위메이드",
            "KOSDAQ",
            "소프트웨어·인터넷·플랫폼",
            "게임 및 블록체인 플랫폼",
            "게임, 플랫폼",
            "Growth",
            "게임 플랫폼과 신사업 모멘텀을 반영하는 KOSDAQ 대표 후보입니다.",
            "2010-01-01",
            kosdaq_note,
        ),
        row(
            20,
            "263750",
            "펄어비스",
            "KOSDAQ",
            "소프트웨어·인터넷·플랫폼",
            "게임 소프트웨어",
            "게임, 글로벌 IP",
            "Growth",
            "글로벌 게임 IP와 신작 기대가 팩터 전략에 반영될 수 있습니다.",
            "2017-09-14",
            kosdaq_note,
        ),
        row(
            21,
            "293490",
            "카카오게임즈",
            "KOSDAQ",
            "소프트웨어·인터넷·플랫폼",
            "게임 퍼블리싱",
            "게임, 플랫폼",
            "Growth",
            "KOSDAQ 게임 대형주로 플랫폼 계열 성장성을 보완합니다.",
            "2020-09-10",
            kosdaq_note,
        ),
        row(
            22,
            "181710",
            "NHN",
            "KOSPI",
            "소프트웨어·인터넷·플랫폼",
            "클라우드 및 결제 플랫폼",
            "클라우드, 결제",
            "Defensive",
            "게임 외 클라우드·결제 매출을 가진 플랫폼 분산 후보입니다.",
            "2013-08-29",
            note,
        ),
        row(
            23,
            "067160",
            "SOOP",
            "KOSDAQ",
            "소프트웨어·인터넷·플랫폼",
            "동영상 플랫폼",
            "플랫폼, 광고",
            "Growth",
            "국내 스트리밍 플랫폼 대표주로 광고와 콘텐츠 성장성을 반영합니다.",
            "2010-01-01",
            kosdaq_note + "; 사명 변경 이력 확인",
        ),
        row(
            24,
            "005380",
            "현대자동차",
            "KOSPI",
            "자동차·모빌리티",
            "완성차",
            "전기차, 모빌리티",
            "Core",
            "국내 완성차 대표주로 수출, 환율, 전기차 사이클을 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            25,
            "000270",
            "기아",
            "KOSPI",
            "자동차·모빌리티",
            "완성차",
            "전기차, SUV",
            "Core",
            "완성차 수익성과 글로벌 판매 모멘텀을 반영하는 고유동성 종목입니다.",
            "2010-01-01",
            note,
        ),
        row(
            26,
            "012330",
            "현대모비스",
            "KOSPI",
            "자동차·모빌리티",
            "자동차 부품",
            "전장, 모듈",
            "Core",
            "자동차 부품과 전동화 부품의 안정적 대표성을 제공합니다.",
            "2010-01-01",
            note,
        ),
        row(
            27,
            "011210",
            "현대위아",
            "KOSPI",
            "자동차·모빌리티",
            "파워트레인 및 기계",
            "모빌리티 부품",
            "Cyclical",
            "자동차 부품 사이클과 기계 사업 변동성을 포착할 수 있습니다.",
            "2011-02-21",
            note,
        ),
        row(
            28,
            "204320",
            "HL만도",
            "KOSPI",
            "자동차·모빌리티",
            "섀시 및 자율주행 부품",
            "자율주행, 전장",
            "Growth",
            "전장화와 자율주행 부품 성장성을 반영하는 자동차 부품주입니다.",
            "2014-10-06",
            note,
        ),
        row(
            29,
            "161390",
            "한국타이어앤테크놀로지",
            "KOSPI",
            "자동차·모빌리티",
            "타이어",
            "자동차 부품",
            "Defensive",
            "글로벌 타이어 수요와 원재료 비용 사이클을 반영합니다.",
            "2012-10-04",
            note,
        ),
        row(
            30,
            "018880",
            "한온시스템",
            "KOSPI",
            "자동차·모빌리티",
            "자동차 열관리",
            "전기차 열관리",
            "Growth",
            "전기차 열관리 부품 노출로 모빌리티 성장 테마를 보완합니다.",
            "2010-01-01",
            note,
        ),
        row(
            31,
            "086280",
            "현대글로비스",
            "KOSPI",
            "자동차·모빌리티",
            "자동차 물류",
            "물류, 완성차 밸류체인",
            "Defensive",
            "완성차 물류와 해운 물류를 연결하는 안정적 현금흐름 후보입니다.",
            "2010-01-01",
            note,
        ),
        row(
            32,
            "373220",
            "LG에너지솔루션",
            "KOSPI",
            "2차전지·소재",
            "배터리 셀",
            "2차전지, 전기차",
            "Core",
            "국내 2차전지 셀 대표주로 글로벌 전기차 밸류체인을 반영합니다.",
            "2022-01-27",
            note,
        ),
        row(
            33,
            "006400",
            "삼성SDI",
            "KOSPI",
            "2차전지·소재",
            "배터리 셀 및 전자재료",
            "2차전지, 전자재료",
            "Core",
            "배터리와 전자재료를 함께 보유한 대형 품질 성장주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            34,
            "247540",
            "에코프로비엠",
            "KOSDAQ",
            "2차전지·소재",
            "양극재",
            "2차전지 소재",
            "Growth",
            "KOSDAQ 2차전지 소재 대표주로 성장성과 유동성이 큽니다.",
            "2019-03-05",
            kosdaq_note,
        ),
        row(
            35,
            "086520",
            "에코프로",
            "KOSDAQ",
            "2차전지·소재",
            "2차전지 소재 지주",
            "2차전지 소재",
            "Growth",
            "배터리 소재 밸류체인 지주 성격으로 테마 대표성이 높습니다.",
            "2010-01-01",
            kosdaq_note,
        ),
        row(
            36,
            "051910",
            "LG화학",
            "KOSPI",
            "2차전지·소재",
            "화학 및 배터리 소재",
            "첨단소재, 배터리",
            "Core",
            "화학 대형주이면서 배터리 소재와 생명과학 노출을 제공합니다.",
            "2010-01-01",
            note,
        ),
        row(
            37,
            "005070",
            "코스모신소재",
            "KOSPI",
            "2차전지·소재",
            "양극활물질 및 필름",
            "2차전지 소재",
            "Growth",
            "양극재 소재 성장성과 중형주 모멘텀을 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            38,
            "361610",
            "SK아이이테크놀로지",
            "KOSPI",
            "2차전지·소재",
            "배터리 분리막",
            "분리막, 전기차",
            "Growth",
            "분리막 업황 회복과 전기차 소재 사이클을 포착할 수 있습니다.",
            "2021-05-11",
            note,
        ),
        row(
            39,
            "003670",
            "포스코퓨처엠",
            "KOSPI",
            "2차전지·소재",
            "양극재 및 음극재",
            "2차전지 소재",
            "Growth",
            "양·음극재를 포함한 배터리 소재 대형 성장주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            40,
            "272290",
            "이녹스첨단소재",
            "KOSDAQ",
            "2차전지·소재",
            "IT 및 배터리 소재",
            "첨단소재",
            "Growth",
            "IT 소재 기반에 배터리 소재 확장성을 가진 KOSDAQ 후보입니다.",
            "2017-07-10",
            kosdaq_note,
        ),
        row(
            41,
            "357780",
            "솔브레인",
            "KOSDAQ",
            "2차전지·소재",
            "반도체 및 배터리 소재",
            "공정소재, 2차전지",
            "Growth",
            "반도체 소재 수익성과 2차전지 소재 선택지를 함께 제공합니다.",
            "2020-08-06",
            kosdaq_note,
        ),
        row(
            42,
            "105560",
            "KB금융",
            "KOSPI",
            "금융",
            "금융지주",
            "은행, 배당",
            "Core",
            "국내 대표 금융지주로 대형 가치주와 배당 팩터를 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            43,
            "055550",
            "신한지주",
            "KOSPI",
            "금융",
            "금융지주",
            "은행, 배당",
            "Core",
            "은행·카드·증권 포트폴리오를 가진 고유동성 금융 대표주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            44,
            "086790",
            "하나금융지주",
            "KOSPI",
            "금융",
            "금융지주",
            "은행, 환율",
            "Core",
            "금리와 환율 민감도가 있는 금융 대형주로 분산 효과가 있습니다.",
            "2010-01-01",
            note,
        ),
        row(
            45,
            "316140",
            "우리금융지주",
            "KOSPI",
            "금융",
            "금융지주",
            "은행, 배당",
            "Core",
            "은행 중심 금융지주로 가치·배당 팩터 적용에 적합합니다.",
            "2019-02-13",
            note,
        ),
        row(
            46,
            "024110",
            "기업은행",
            "KOSPI",
            "금융",
            "은행",
            "은행, 배당",
            "Defensive",
            "정책금융 성격과 안정적 배당 특성을 가진 은행주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            47,
            "032830",
            "삼성생명",
            "KOSPI",
            "금융",
            "생명보험",
            "보험, 금리",
            "Defensive",
            "보험 섹터 대표주로 금리 민감도와 안정성을 제공합니다.",
            "2010-05-12",
            note,
        ),
        row(
            48,
            "000810",
            "삼성화재해상보험",
            "KOSPI",
            "금융",
            "손해보험",
            "보험, 배당",
            "Defensive",
            "손해보험 대표주로 방어적 이익과 배당 성격을 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            49,
            "005940",
            "NH투자증권",
            "KOSPI",
            "금융",
            "증권",
            "증권, 자본시장",
            "Cyclical",
            "거래대금과 자본시장 사이클에 민감한 증권 대표 종목입니다.",
            "2010-01-01",
            note,
        ),
        row(
            50,
            "039490",
            "키움증권",
            "KOSPI",
            "금융",
            "온라인 증권",
            "증권, 브로커리지",
            "Cyclical",
            "개인 거래대금 변화와 온라인 브로커리지 강점을 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            51,
            "071050",
            "한국금융지주",
            "KOSPI",
            "금융",
            "금융투자 지주",
            "증권, 투자은행",
            "Cyclical",
            "증권·운용·IB 사이클에 대한 금융 섹터 분산 후보입니다.",
            "2010-01-01",
            note,
        ),
        row(
            52,
            "207940",
            "삼성바이오로직스",
            "KOSPI",
            "바이오·헬스케어",
            "바이오 CDMO",
            "바이오, CDMO",
            "Core",
            "글로벌 바이오 위탁생산 대표주로 성장성과 방어성을 함께 갖췄습니다.",
            "2016-11-10",
            note,
        ),
        row(
            53,
            "068270",
            "셀트리온",
            "KOSPI",
            "바이오·헬스케어",
            "바이오시밀러",
            "바이오, 헬스케어",
            "Core",
            "국내 바이오시밀러 대표주로 유동성과 장기 데이터 활용도가 높습니다.",
            "2010-01-01",
            note,
        ),
        row(
            54,
            "128940",
            "한미약품",
            "KOSPI",
            "바이오·헬스케어",
            "제약 및 신약개발",
            "신약, 제약",
            "Growth",
            "신약 파이프라인과 제약 영업 기반을 함께 보유한 후보입니다.",
            "2010-07-30",
            note,
        ),
        row(
            55,
            "302440",
            "SK바이오사이언스",
            "KOSPI",
            "바이오·헬스케어",
            "백신 및 바이오",
            "백신, 바이오",
            "Growth",
            "백신 플랫폼과 바이오 생산 역량을 반영하는 성장 후보입니다.",
            "2021-03-18",
            note,
        ),
        row(
            56,
            "326030",
            "에스케이바이오팜",
            "KOSPI",
            "바이오·헬스케어",
            "신약 개발",
            "신약, CNS",
            "Growth",
            "글로벌 신약 상업화 경험을 가진 바이오 성장주입니다.",
            "2020-07-02",
            note,
        ),
        row(
            57,
            "196170",
            "알테오젠",
            "KOSDAQ",
            "바이오·헬스케어",
            "바이오 플랫폼",
            "바이오, 기술이전",
            "Growth",
            "플랫폼 기술과 기술이전 모멘텀을 가진 KOSDAQ 바이오 대표주입니다.",
            "2014-12-12",
            kosdaq_note,
        ),
        row(
            58,
            "028300",
            "HLB",
            "KOSDAQ",
            "바이오·헬스케어",
            "신약 개발",
            "바이오, 항암",
            "Growth",
            "대형 KOSDAQ 바이오 종목으로 이벤트와 모멘텀 팩터 적용성이 큽니다.",
            "2010-01-01",
            kosdaq_note,
        ),
        row(
            59,
            "214450",
            "파마리서치",
            "KOSDAQ",
            "바이오·헬스케어",
            "재생의학 및 의료미용",
            "헬스케어, 미용",
            "Growth",
            "의료미용 수요와 수익성 개선을 반영하는 중형 성장주입니다.",
            "2015-07-24",
            kosdaq_note,
        ),
        row(
            60,
            "145020",
            "휴젤",
            "KOSDAQ",
            "바이오·헬스케어",
            "보툴리눔 톡신",
            "의료미용, 바이오",
            "Growth",
            "의료미용 분야의 글로벌 확장성과 현금창출력을 갖춘 후보입니다.",
            "2015-12-24",
            kosdaq_note,
        ),
        row(
            61,
            "214150",
            "클래시스",
            "KOSDAQ",
            "바이오·헬스케어",
            "미용 의료기기",
            "의료기기, 미용",
            "Growth",
            "미용 의료기기 수출 성장성과 높은 수익성을 반영합니다.",
            "2017-12-28",
            kosdaq_note,
        ),
        row(
            62,
            "012450",
            "한화에어로스페이스",
            "KOSPI",
            "방산·항공우주",
            "방산 및 항공엔진",
            "방산, 항공우주",
            "Core",
            "국내 방산 수출과 항공우주 밸류체인을 대표하는 고유동성 종목입니다.",
            "2010-01-01",
            note,
        ),
        row(
            63,
            "079550",
            "LIG디펜스앤에어로스페이스",
            "KOSPI",
            "방산·항공우주",
            "유도무기 및 방산전자",
            "방산, 미사일",
            "Growth",
            "방산 수출 성장성과 정밀무기 테마를 반영하는 대표 종목입니다.",
            "2015-10-02",
            note + "; 구 LIG넥스원",
        ),
        row(
            64,
            "047810",
            "한국항공우주",
            "KOSPI",
            "방산·항공우주",
            "항공기 및 우주항공",
            "항공우주, 방산",
            "Growth",
            "항공기 개발과 우주항공 정책 수혜를 반영하는 후보입니다.",
            "2011-06-30",
            note,
        ),
        row(
            65,
            "272210",
            "한화시스템",
            "KOSPI",
            "방산·항공우주",
            "방산전자 및 ICT",
            "방산, 위성, ICT",
            "Growth",
            "방산전자와 위성·ICT 성장 테마를 동시에 제공합니다.",
            "2019-11-13",
            note,
        ),
        row(
            66,
            "064350",
            "현대로템",
            "KOSPI",
            "방산·항공우주",
            "철도 및 방산",
            "방산, 철도",
            "Cyclical",
            "전차 수출과 철도 인프라 사이클을 함께 반영합니다.",
            "2013-10-30",
            note,
        ),
        row(
            67,
            "003490",
            "대한항공",
            "KOSPI",
            "방산·항공우주",
            "항공운송 및 항공우주",
            "항공, 방산",
            "Cyclical",
            "항공운송 사이클과 항공우주 제조 노출을 보완합니다.",
            "2010-01-01",
            note,
        ),
        row(
            68,
            "009540",
            "HD한국조선해양",
            "KOSPI",
            "조선·기계·산업재",
            "조선 지주",
            "조선, LNG선",
            "Core",
            "국내 조선업 대표 지주사로 선박 사이클을 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            69,
            "329180",
            "HD현대중공업",
            "KOSPI",
            "조선·기계·산업재",
            "조선",
            "조선, 방산",
            "Cyclical",
            "대형 조선 수주 사이클과 선가 모멘텀을 반영하는 핵심 후보입니다.",
            "2021-09-17",
            note,
        ),
        row(
            70,
            "010140",
            "삼성중공업",
            "KOSPI",
            "조선·기계·산업재",
            "조선 및 해양플랜트",
            "조선, LNG선",
            "Cyclical",
            "조선 업황 회복과 해양플랜트 사이클을 포착할 수 있습니다.",
            "2010-01-01",
            note,
        ),
        row(
            71,
            "042660",
            "한화오션",
            "KOSPI",
            "조선·기계·산업재",
            "조선 및 특수선",
            "조선, 방산",
            "Cyclical",
            "상선과 특수선 수주를 함께 반영하는 조선 대표 후보입니다.",
            "2010-01-01",
            note,
        ),
        row(
            72,
            "267260",
            "HD현대일렉트릭",
            "KOSPI",
            "조선·기계·산업재",
            "전력기기",
            "전력망, 변압기",
            "Growth",
            "전력망 투자와 변압기 수출 성장성을 반영하는 산업재 성장주입니다.",
            "2017-05-10",
            note,
        ),
        row(
            73,
            "034020",
            "두산에너빌리티",
            "KOSPI",
            "조선·기계·산업재",
            "발전설비 및 원전",
            "원전, 산업재",
            "Cyclical",
            "원전과 발전설비 투자 사이클을 반영하는 대형 산업재입니다.",
            "2010-01-01",
            note,
        ),
        row(
            74,
            "241560",
            "두산밥캣",
            "KOSPI",
            "조선·기계·산업재",
            "건설기계",
            "건설기계, 인프라",
            "Cyclical",
            "북미 건설기계 수요와 인프라 투자를 반영합니다.",
            "2016-11-18",
            note,
        ),
        row(
            75,
            "443060",
            "HD현대마린솔루션",
            "KOSPI",
            "조선·기계·산업재",
            "선박 애프터마켓 서비스",
            "조선, 선박서비스",
            "Growth",
            "선박 유지보수와 친환경 개조 수요를 반영하는 조선 밸류체인 후보입니다.",
            "2024-05-08",
            note,
        ),
        row(
            76,
            "096770",
            "SK이노베이션",
            "KOSPI",
            "에너지·화학",
            "정유 및 배터리",
            "정유, 배터리",
            "Cyclical",
            "정유 마진과 배터리 사업 가치를 함께 반영하는 대형주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            77,
            "010950",
            "S-Oil",
            "KOSPI",
            "에너지·화학",
            "정유",
            "정유, 배당",
            "Cyclical",
            "정제마진과 유가 사이클을 반영하는 고유동성 에너지 종목입니다.",
            "2010-01-01",
            note,
        ),
        row(
            78,
            "009830",
            "한화솔루션",
            "KOSPI",
            "에너지·화학",
            "화학 및 태양광",
            "태양광, 화학",
            "Cyclical",
            "태양광과 기초화학 사이클을 함께 반영하는 후보입니다.",
            "2010-01-01",
            note,
        ),
        row(
            79,
            "011170",
            "롯데케미칼",
            "KOSPI",
            "에너지·화학",
            "석유화학",
            "화학, 경기민감",
            "Cyclical",
            "석유화학 업황과 스프레드 회복을 반영하는 대표주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            80,
            "011780",
            "금호석유화학",
            "KOSPI",
            "에너지·화학",
            "합성고무 및 화학",
            "화학, 소재",
            "Cyclical",
            "합성고무와 화학 스프레드 사이클을 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            81,
            "004020",
            "현대제철",
            "KOSPI",
            "에너지·화학",
            "철강",
            "철강, 자동차 소재",
            "Cyclical",
            "철강 수요와 자동차·건설 경기 민감도를 보완합니다.",
            "2010-01-01",
            note,
        ),
        row(
            82,
            "005490",
            "POSCO홀딩스",
            "KOSPI",
            "에너지·화학",
            "철강 및 소재 지주",
            "철강, 배터리 소재",
            "Core",
            "철강 대표성과 배터리 소재 성장성을 함께 가진 대형주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            83,
            "010130",
            "고려아연",
            "KOSPI",
            "에너지·화학",
            "비철금속 제련",
            "비철금속, 소재",
            "Defensive",
            "비철금속 제련과 배터리 소재 확장성을 가진 안정적 소재주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            84,
            "051900",
            "LG생활건강",
            "KOSPI",
            "소비재·유통·엔터테인먼트",
            "화장품 및 생활용품",
            "소비재, 화장품",
            "Defensive",
            "생활용품과 화장품 브랜드를 보유한 소비재 대표주입니다.",
            "2010-01-01",
            note,
        ),
        row(
            85,
            "090430",
            "아모레퍼시픽",
            "KOSPI",
            "소비재·유통·엔터테인먼트",
            "화장품",
            "K뷰티, 소비재",
            "Cyclical",
            "화장품 수출과 중국·글로벌 소비 회복을 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            86,
            "097950",
            "CJ제일제당",
            "KOSPI",
            "소비재·유통·엔터테인먼트",
            "식품 및 바이오",
            "식품, 바이오소재",
            "Defensive",
            "식품 방어성과 바이오 소재 성장성을 함께 제공합니다.",
            "2010-01-01",
            note,
        ),
        row(
            87,
            "271560",
            "오리온",
            "KOSPI",
            "소비재·유통·엔터테인먼트",
            "음식료",
            "식품, 해외소비",
            "Defensive",
            "해외 매출 기반의 음식료 안정성을 반영하는 소비재 후보입니다.",
            "2017-07-07",
            note,
        ),
        row(
            88,
            "139480",
            "이마트",
            "KOSPI",
            "소비재·유통·엔터테인먼트",
            "대형마트 및 유통",
            "유통, 내수",
            "Cyclical",
            "내수 소비와 유통 구조 변화에 대한 노출을 제공합니다.",
            "2011-06-10",
            note,
        ),
        row(
            89,
            "383220",
            "F&F",
            "KOSPI",
            "소비재·유통·엔터테인먼트",
            "패션",
            "패션, 소비재",
            "Growth",
            "브랜드 기반 소비재 성장성과 해외 확장성을 반영합니다.",
            "2021-05-21",
            note,
        ),
        row(
            90,
            "352820",
            "하이브",
            "KOSPI",
            "소비재·유통·엔터테인먼트",
            "엔터테인먼트",
            "K팝, 콘텐츠",
            "Growth",
            "K팝 지식재산권과 글로벌 팬덤 경제를 대표하는 성장주입니다.",
            "2020-10-15",
            note,
        ),
        row(
            91,
            "035900",
            "JYP Ent.",
            "KOSDAQ",
            "소비재·유통·엔터테인먼트",
            "엔터테인먼트",
            "K팝, 콘텐츠",
            "Growth",
            "KOSDAQ 엔터 대표주로 글로벌 콘텐츠 성장성을 반영합니다.",
            "2010-01-01",
            kosdaq_note,
        ),
        row(
            92,
            "017670",
            "SK텔레콤",
            "KOSPI",
            "통신·인프라",
            "무선통신",
            "통신, AI 인프라",
            "Defensive",
            "통신 방어성과 AI 데이터센터 신사업 노출을 함께 제공합니다.",
            "2010-01-01",
            note,
        ),
        row(
            93,
            "030200",
            "케이티",
            "KOSPI",
            "통신·인프라",
            "유무선통신",
            "통신, 클라우드",
            "Defensive",
            "유무선 통신 기반의 안정적 현금흐름과 배당 성격을 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            94,
            "032640",
            "LG유플러스",
            "KOSPI",
            "통신·인프라",
            "무선통신",
            "통신, 미디어",
            "Defensive",
            "통신 3사 분산과 내수 방어주 특성을 제공합니다.",
            "2010-01-01",
            note,
        ),
        row(
            95,
            "365340",
            "성일하이텍",
            "KOSDAQ",
            "통신·인프라",
            "배터리 리사이클링 인프라",
            "순환자원, 인프라",
            "Growth",
            "배터리 재활용 인프라 성장성을 반영하는 KOSDAQ 후보입니다.",
            "2022-07-28",
            kosdaq_note,
        ),
        row(
            96,
            "000720",
            "현대건설",
            "KOSPI",
            "건설·운송·기타",
            "건설 및 플랜트",
            "건설, 원전, 인프라",
            "Cyclical",
            "국내외 건설·플랜트와 원전 인프라 사이클을 반영합니다.",
            "2010-01-01",
            note,
        ),
        row(
            97,
            "006360",
            "GS건설",
            "KOSPI",
            "건설·운송·기타",
            "건설",
            "건설, 인프라",
            "Cyclical",
            "주택과 인프라 경기 변동성을 반영하는 건설 대표 종목입니다.",
            "2010-01-01",
            note,
        ),
        row(
            98,
            "047040",
            "대우건설",
            "KOSPI",
            "건설·운송·기타",
            "건설",
            "건설, 해외수주",
            "Cyclical",
            "해외수주와 주택 경기 회복 모멘텀을 포착할 수 있습니다.",
            "2010-01-01",
            note,
        ),
        row(
            99,
            "028260",
            "삼성물산",
            "KOSPI",
            "건설·운송·기타",
            "상사·건설·패션 지주",
            "지주, 건설, 상사",
            "Core",
            "건설, 상사, 바이오 지분가치를 함께 가진 복합 대형주입니다.",
            "2014-12-18",
            note,
        ),
        row(
            100,
            "011200",
            "HMM",
            "KOSPI",
            "건설·운송·기타",
            "해운",
            "해운, 운송",
            "Cyclical",
            "컨테이너 운임 사이클을 반영하는 운송 대표주입니다.",
            "2010-01-01",
            note,
        ),
    ]


def validate_universe(rows: Iterable[dict[str, object]]) -> None:
    """Validate generated rows and raise ValueError with clear messages."""
    data = list(rows)
    errors: list[str] = []

    if len(data) != 100:
        errors.append(f"전체 종목 수가 100개가 아닙니다: {len(data)}")

    ranks = [int(item["rank"]) for item in data]
    if ranks != list(range(1, 101)):
        errors.append("rank가 1부터 100까지 연속적이지 않습니다.")

    tickers = [str(item["ticker"]) for item in data]
    if any(len(ticker) != 6 or not ticker.isdigit() for ticker in tickers):
        errors.append("ticker는 모두 6자리 숫자 문자열이어야 합니다.")
    duplicates = [ticker for ticker, count in Counter(tickers).items() if count > 1]
    if duplicates:
        errors.append(f"중복 ticker가 있습니다: {duplicates}")

    names = [str(item["company_name"]) for item in data]
    duplicate_names = [name for name, count in Counter(names).items() if count > 1]
    if duplicate_names:
        errors.append(f"중복 company_name이 있습니다: {duplicate_names}")

    markets = {str(item["market"]) for item in data}
    invalid_markets = markets - VALID_MARKETS
    if invalid_markets:
        errors.append(f"market 값이 허용 범위를 벗어났습니다: {sorted(invalid_markets)}")

    roles = {str(item["universe_role"]) for item in data}
    invalid_roles = roles - VALID_ROLES
    if invalid_roles:
        errors.append(f"universe_role 값이 허용 범위를 벗어났습니다: {sorted(invalid_roles)}")

    for index, item in enumerate(data, start=1):
        missing = [column for column in CSV_COLUMNS if item.get(column) in ("", None)]
        if missing:
            errors.append(f"{index}행 필수 컬럼 결측치: {missing}")

    sector_counts = Counter(str(item["sector"]) for item in data)
    over_limit = {
        sector: count
        for sector, count in sector_counts.items()
        if count / len(data) > MAX_SECTOR_WEIGHT
    }
    if over_limit:
        errors.append(f"단일 sector 비중이 25%를 초과했습니다: {over_limit}")

    if errors:
        raise ValueError("\n".join(errors))


def write_csv(rows: list[dict[str, object]], output_path: Path) -> None:
    """Write rows to UTF-8-SIG CSV for Korean Excel compatibility."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.DictWriter(file, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    """Build, validate, and save the universe CSV."""
    try:
        rows = build_universe()
        validate_universe(rows)
        write_csv(rows, OUTPUT_PATH)
    except Exception as exc:  # noqa: BLE001 - command-line script should print clear failures.
        raise SystemExit(f"유니버스 생성 실패:\n{exc}") from exc

    print(f"유니버스 CSV 생성 완료: {OUTPUT_PATH}")
    print(f"종목 수: {len(rows)}")
    print("검증 통과")


if __name__ == "__main__":
    main()
